/* Signal Ledger page: asymmetrical editorial rails and clear route signals make URL shortening feel focused and deliberate. */
import { BrandMark } from "@/components/brand-mark";
import { LinkShortener } from "@/components/link-shortener";
import { RouteArt } from "@/components/route-art";
import { RouteSignal } from "@/components/route-signal";
import { ThemeToggle } from "@/components/theme-toggle";
import { ArrowDown, ArrowUpRight, BarChart3, Link2, MousePointer2, ShieldCheck } from "lucide-react";

const steps = [
  ["01", "Tempel URL", "Masukkan alamat tujuan dengan protokol http:// atau https://.", "alamat masuk"],
  ["02", "Pilih identitas", "Gunakan kode enam karakter atau tulis alias yang Anda inginkan.", "kode diringkas"],
  ["03", "Bagikan & ukur", "Setiap kunjungan dialihkan ke tujuan dan dicatat otomatis.", "jejak tercatat"],
];

export default function HomePage() {
  return (
    <main className="min-h-screen overflow-x-hidden bg-[var(--canvas)] text-[var(--ink)]">
      <header className="mx-auto flex max-w-[1440px] items-center justify-between px-5 py-5 sm:px-8 lg:px-12 lg:py-7">
        <BrandMark />
        <div className="flex items-center gap-3"><a href="#cara-kerja" className="hidden rounded-sm px-2 py-2 font-mono-brand text-[11px] font-medium text-[var(--ink-soft)] transition hover:text-[var(--ink)] sm:block">Cara kerja</a><ThemeToggle /></div>
      </header>

      <section className="ledger-section mx-auto max-w-[1440px] px-5 pb-16 pt-6 sm:px-8 lg:px-12 lg:pb-28 lg:pt-10">
        <div className="grid gap-10 lg:grid-cols-[minmax(280px,.78fr)_minmax(560px,1.22fr)] lg:gap-16">
          <div className="flex flex-col justify-between lg:min-h-[650px]">
            <div><RouteSignal label="URL / 01 → relay" className="mb-7 max-w-[210px]" /><h1 className="max-w-[570px] text-[clamp(3.4rem,7vw,7.4rem)] font-extrabold leading-[.88] tracking-[-.075em] text-[var(--ink)]">Tautan panjang,<span className="font-display block font-normal italic tracking-[-.065em] text-[var(--signal)]">keputusan singkat.</span></h1><p className="mt-8 max-w-sm text-[15px] leading-7 text-[var(--ink-soft)] sm:text-base">Buat alamat yang ringkas, mudah dibagikan, dan memiliki jejak kunjungan yang jelas — tanpa kerumitan.</p></div>
            <div className="mt-12 hidden lg:block"><div className="flex items-center gap-4"><div className="grid size-11 place-items-center rounded-full bg-[var(--ink)] text-[var(--paper)]"><ArrowDown className="size-4" /></div><div><p className="font-mono-brand text-[10px] font-medium uppercase tracking-[.17em] text-[var(--ink-soft)]">Tidak ada akun</p><p className="mt-1 text-sm font-semibold text-[var(--ink)]">Langsung ke inti pekerjaan.</p></div></div><RouteSignal label="tempel untuk memulai" className="ml-5 mt-5 max-w-[220px]" /></div>
          </div>
          <div className="relative pt-2 lg:pt-8"><div className="absolute -right-24 -top-8 hidden size-56 rounded-full border border-[var(--line)] lg:block" /><div className="relative"><div className="absolute -right-2 -top-5 z-10 hidden rounded-full border border-[var(--line)] bg-[var(--canvas)] px-4 py-2 font-mono-brand text-[10px] font-medium uppercase tracking-[.16em] text-[var(--ink-soft)] shadow-sm sm:block">satu tujuan, satu rute</div><LinkShortener /></div><div className="relative mt-7 overflow-hidden border border-[var(--line)] p-2 shadow-[10px_10px_0_color-mix(in_srgb,var(--ink)_7%,transparent)] sm:p-3"><RouteArt variant="hero" /><div className="absolute bottom-7 left-6 rounded-[3px] bg-[var(--ink)] px-3 py-2 font-mono-brand text-[10px] font-medium uppercase tracking-[.15em] text-[var(--paper)] sm:bottom-8 sm:left-8">https://alamat-panjang… <span className="text-[var(--signal)]">→</span> /a8m2ky</div></div></div>
        </div>
      </section>

      <section id="cara-kerja" className="ledger-section border-y border-[var(--line)] bg-[var(--paper)]"><div className="mx-auto grid max-w-[1440px] gap-10 px-5 py-16 sm:px-8 lg:grid-cols-[.78fr_1.22fr] lg:gap-16 lg:px-12 lg:py-24"><div><RouteSignal label="02 / perjalanan link" className="max-w-[210px]" /><h2 className="mt-5 max-w-md text-4xl font-extrabold leading-[.97] tracking-[-.06em] sm:text-5xl">Sedikit langkah. Banyak kejelasan.</h2><p className="mt-6 max-w-sm leading-7 text-[var(--ink-soft)]">Pendek menyimpan tujuan, membuat pengenal yang aman, lalu mencatat setiap pengalihan di sisi server.</p><div className="mt-9 hidden w-44 lg:block"><RouteArt variant="ledger" /></div></div><div className="divide-y divide-[var(--line)] border-y border-[var(--line)]">{steps.map(([number,title,copy,status]) => <article key={number} className="group grid gap-5 py-7 sm:grid-cols-[72px_1fr_auto] sm:items-start sm:py-9"><span className="font-mono-brand text-2xl text-[var(--signal)]">{number}</span><div><h3 className="text-xl font-extrabold tracking-[-.045em]">{title}</h3><p className="mt-2 max-w-lg text-sm leading-6 text-[var(--ink-soft)]">{copy}</p><RouteSignal label={status} className="mt-4 max-w-[220px]" /></div><ArrowUpRight className="hidden size-5 text-[var(--ink-soft)] transition duration-180 group-hover:-translate-y-1 group-hover:translate-x-1 group-hover:text-[var(--signal)] sm:block" /></article>)}</div></div></section>

      <section className="ledger-section mx-auto max-w-[1440px] px-5 py-16 sm:px-8 lg:px-12 lg:py-24"><div className="grid gap-8 lg:grid-cols-[1.22fr_.78fr] lg:items-end"><div className="border-l-2 border-[var(--signal)] pl-5 sm:pl-7"><RouteSignal label="03 / jejak kunjungan" className="max-w-[210px]" /><h2 className="mt-5 max-w-2xl text-4xl font-extrabold leading-[.97] tracking-[-.06em] sm:text-5xl">Setiap klik meninggalkan catatan.</h2><p className="mt-6 max-w-xl leading-7 text-[var(--ink-soft)]">Pengalihan tetap cepat, sementara penghitung klik dan waktu kunjungan terakhir diperbarui secara atomik di PostgreSQL.</p></div><div className="flex gap-3 sm:justify-end"><div className="flex items-center gap-2 rounded-[4px] border border-[var(--line)] bg-[var(--paper)] px-4 py-3 font-mono-brand text-[11px] text-[var(--ink-soft)]"><MousePointer2 className="size-4 text-[var(--signal)]" />klik terukur</div><div className="flex items-center gap-2 rounded-[4px] border border-[var(--line)] bg-[var(--paper)] px-4 py-3 font-mono-brand text-[11px] text-[var(--ink-soft)]"><ShieldCheck className="size-4 text-[var(--signal)]" />tujuan tervalidasi</div></div></div><div className="mt-10 grid overflow-hidden border border-[var(--line)] bg-[var(--paper)] lg:grid-cols-[1fr_.9fr]"><div className="p-7 sm:p-10"><div className="flex items-start justify-between gap-5 border-b border-[var(--line)] pb-6"><div><RouteSignal label="rekam / terbuka" className="max-w-[190px]" /><p className="mt-3 font-mono-brand text-lg font-medium tracking-[-.06em]">/a8m2ky</p></div><div className="grid size-11 place-items-center rounded-full bg-[var(--ink)] text-[var(--paper)]"><BarChart3 className="size-4" /></div></div><div className="mt-7 grid grid-cols-2 gap-5"><div><p className="font-mono-brand text-[10px] uppercase tracking-[.14em] text-[var(--ink-soft)]">kunjungan</p><p className="mt-2 text-3xl font-extrabold tracking-[-.07em]">—</p></div><div><p className="font-mono-brand text-[10px] uppercase tracking-[.14em] text-[var(--ink-soft)]">terakhir</p><p className="mt-2 text-sm font-bold">Menunggu klik</p></div></div><p className="mt-7 text-sm leading-6 text-[var(--ink-soft)]">Setelah tautan dibuat, buka halaman catatan untuk melihat angka aktual dari database.</p></div><RouteArt variant="clicks" /></div></section>

      <footer className="border-t border-[var(--line)] bg-[var(--ink)] text-[var(--paper)]"><div className="mx-auto flex max-w-[1440px] flex-col gap-8 px-5 py-10 sm:px-8 md:flex-row md:items-end md:justify-between lg:px-12"><div><div className="flex items-center gap-3"><Link2 className="size-5 text-[var(--signal)]" /><span className="font-mono-brand text-xl tracking-[-.15em]">pend<span className="mx-[2px] inline-block size-[6px] rounded-full bg-[var(--signal)]" />ek</span></div><RouteSignal label="pendek / rute yang lebih jelas" className="mt-5 max-w-[260px] text-[#c2d1c8]" /><p className="mt-4 max-w-sm text-sm leading-6 text-[#c2d1c8]">Pemendek URL untuk portofolio dan pekerjaan digital yang membutuhkan jalur singkat.</p></div><div className="font-mono-brand text-[10px] uppercase tracking-[.16em] text-[#c2d1c8]">dibuat oleh Abia Nugrahanto</div></div></footer>
    </main>
  );
}

