/* Signal Ledger component: functional route diagrams visualise shortening and analytics without relying on generic decoration. */
type RouteArtProps = { variant: "hero" | "ledger" | "clicks" };

export function RouteArt({ variant }: RouteArtProps) {
  if (variant === "ledger") {
    return <div aria-hidden className="relative h-56 overflow-hidden border border-[var(--line)] bg-[var(--paper-deep)] shadow-[7px_7px_0_color-mix(in_srgb,var(--ink)_9%,transparent)]"><div className="absolute left-7 top-7 font-mono-brand text-[9px] uppercase tracking-[.18em] text-[var(--ink-soft)]">transit / 02</div><span className="absolute left-8 top-16 size-3 rounded-full border-2 border-[var(--signal)] bg-[var(--paper)]" /><span className="absolute left-[42px] top-24 h-24 w-px bg-[repeating-linear-gradient(to_bottom,var(--ink)_0_4px,transparent_4px_9px)]" /><span className="absolute bottom-9 left-[42px] h-px w-24 bg-[repeating-linear-gradient(to_right,var(--ink)_0_4px,transparent_4px_9px)]" /><span className="absolute bottom-[31px] left-[132px] size-4 rounded-full bg-[var(--signal)] shadow-[0_0_0_5px_var(--signal-soft)]" /><span className="absolute bottom-[37px] left-[160px] h-px w-10 bg-[var(--ink)]" /><span className="absolute bottom-[31px] right-7 grid size-4 place-items-center rounded-full bg-[var(--ink)] text-[7px] text-[var(--paper)]">✓</span></div>;
  }
  if (variant === "clicks") {
    return <div aria-hidden className="relative h-64 overflow-hidden border-t border-[var(--line)] bg-[var(--paper-deep)] lg:h-full lg:border-l lg:border-t-0"><div className="absolute left-8 top-8 font-mono-brand text-[9px] uppercase tracking-[.18em] text-[var(--ink-soft)]">log / klik</div><div className="absolute bottom-10 left-8 right-8 h-px bg-[var(--ink-soft)] opacity-30" /><div className="absolute bottom-10 left-10 flex h-36 items-end gap-3"><i className="w-6 bg-[var(--sage)]" style={{ height: "31%" }} /><i className="w-6 bg-[var(--ink-soft)]" style={{ height: "48%" }} /><i className="w-6 bg-[var(--sage)]" style={{ height: "57%" }} /><i className="w-6 bg-[var(--ink)]" style={{ height: "75%" }} /><i className="w-6 bg-[var(--signal)]" style={{ height: "94%" }} /></div><span className="absolute bottom-[163px] left-[213px] size-3 rounded-full border-2 border-[var(--paper)] bg-[var(--signal)] shadow-[0_0_0_5px_color-mix(in_srgb,var(--signal)_26%,transparent)]" /><span className="absolute bottom-[168px] left-[225px] right-9 h-px bg-[repeating-linear-gradient(to_right,var(--ink)_0_4px,transparent_4px_9px)]" /><span className="absolute right-8 top-16 rounded-full border border-[var(--line)] bg-[var(--paper)] px-3 py-2 font-mono-brand text-[9px] text-[var(--ink)]">+ 1 kunjungan</span></div>;
  }
  return <div aria-hidden className="relative h-[220px] overflow-hidden bg-[var(--paper-deep)] sm:h-[270px]"><div className="absolute left-7 top-7 font-mono-brand text-[9px] uppercase tracking-[.18em] text-[var(--ink-soft)]">rute / aktif</div><div className="absolute -bottom-20 -left-20 size-64 rounded-full border-[18px] border-[var(--ink)] opacity-95" /><div className="absolute left-[23%] top-[35%] h-px w-[48%] rotate-[-17deg] bg-[repeating-linear-gradient(to_right,var(--ink)_0_5px,transparent_5px_11px)]" /><span className="absolute left-[54%] top-[39%] grid size-7 place-items-center rounded-full bg-[var(--signal)] text-xs font-bold text-[var(--paper)] shadow-[0_0_0_8px_color-mix(in_srgb,var(--signal)_22%,transparent)]">→</span><div className="absolute right-[11%] top-[21%] grid size-28 place-items-center rounded-[12px] border border-[var(--ink)] bg-[var(--paper)] shadow-[5px_5px_0_var(--ink)]"><span className="font-mono-brand text-2xl font-medium tracking-[-.12em] text-[var(--ink)]">a8m2ky</span><span className="mt-2 font-mono-brand text-[8px] uppercase tracking-[.18em] text-[var(--ink-soft)]">6 digit</span></div><span className="absolute bottom-6 right-8 size-3 rounded-full bg-[var(--sage)]" /></div>;
}
