/* Signal Ledger page: analytics is a restrained public ledger focused on one link and its actual facts. */
import { BrandMark } from "@/components/brand-mark";
import { isPermittedShortCode, normalizeShortCode } from "@/lib/short-code";
import { prisma } from "@/lib/prisma";
import { ArrowLeft, ExternalLink, MousePointer2 } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
export const dynamic = "force-dynamic";
function formatDate(date:Date|null) { if (!date) return "Belum ada kunjungan"; return new Intl.DateTimeFormat("id-ID",{ dateStyle:"medium",timeStyle:"short" }).format(date); }
export default async function InsightPage({ params }:{ params:Promise<{ shortCode:string }> }) { const { shortCode:raw }=await params; const shortCode=normalizeShortCode(raw); if(!isPermittedShortCode(shortCode)) notFound(); const link=await prisma.link.findUnique({ where:{ shortCode } }); if(!link) notFound(); return <main className="min-h-screen bg-[var(--canvas)] px-5 py-5 text-[var(--ink)] sm:px-8 lg:px-12 lg:py-7"><header className="mx-auto flex max-w-[1120px] items-center justify-between"><BrandMark /><Link href="/" className="inline-flex items-center gap-2 font-mono-brand text-[11px] font-medium text-[var(--ink-soft)] transition hover:text-[var(--signal)]"><ArrowLeft className="size-4" />ruang kerja</Link></header><section className="mx-auto mt-16 max-w-[1120px] lg:mt-24"><p className="font-mono-brand text-[10px] font-medium uppercase tracking-[.2em] text-[var(--ink-soft)]">catatan / {link.shortCode}</p><div className="mt-5 grid gap-8 lg:grid-cols-[1.15fr_.85fr]"><div className="paper-grain border border-[var(--line)] bg-[var(--paper)] p-7 shadow-[8px_8px_0_color-mix(in_srgb,var(--ink)_8%,transparent)] sm:p-10"><p className="font-mono-brand text-[10px] font-medium uppercase tracking-[.18em] text-[var(--ink-soft)]">tautan pendek</p><a href={`/${link.shortCode}`} className="mt-4 block break-all font-mono-brand text-3xl font-medium tracking-[-.08em] text-[var(--ink)] underline decoration-[var(--signal)] decoration-[3px] underline-offset-8 sm:text-5xl">/{link.shortCode}</a><div className="mt-12 border-t border-[var(--line)] pt-5"><p className="font-mono-brand text-[10px] font-medium uppercase tracking-[.18em] text-[var(--ink-soft)]">tujuan</p><a href={link.originalUrl} target="_blank" rel="noreferrer" className="mt-3 flex max-w-full items-start gap-2 break-all text-sm leading-6 text-[var(--ink-soft)] transition hover:text-[var(--signal)]"><span>{link.originalUrl}</span><ExternalLink className="mt-1 size-3.5 shrink-0" /></a></div></div><aside className="border border-[var(--line)] bg-[var(--ink)] p-7 text-[var(--paper)] shadow-[8px_8px_0_var(--signal)] sm:p-10"><div className="flex size-11 items-center justify-center rounded-full bg-[var(--signal)]"><MousePointer2 className="size-5" /></div><p className="mt-9 font-mono-brand text-[10px] font-medium uppercase tracking-[.18em] text-[#c2d1c8]">total kunjungan</p><p className="mt-3 text-7xl font-extrabold tracking-[-.09em]">{link.clicks}</p><div className="mt-10 border-t border-white/15 pt-5"><p className="font-mono-brand text-[10px] font-medium uppercase tracking-[.18em] text-[#c2d1c8]">kunjungan terakhir</p><p className="mt-2 text-sm font-semibold leading-6">{formatDate(link.lastVisitedAt)}</p></div></aside></div></section></main>; }
